# Generated by Django 3.0.8 on 2020-08-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_recurso_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='observacoes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
